--Alineación de entornos (Objetos)

--"_SYS_REPO"."CATALOG_OBJECTS_CREATED_BY_REPOSITORY_ACTIVATIONS"

SELECT count(DISTINCT REPOSITORY_OBJECT_NAME ) FROM "_SYS_REPO"."CATALOG_OBJECTS_CREATED_BY_REPOSITORY_ACTIVATIONS"
WHERE REPOSITORY_PACKAGE_ID  = 'AreaSIBI.Proyectos.Maestras'
AND REPOSITORY_OBJECT_TYPE = 'calculationview'

SELECT DISTINCT REPOSITORY_PACKAGE_ID FROM "_SYS_REPO"."CATALOG_OBJECTS_CREATED_BY_REPOSITORY_ACTIVATIONS"

--"_SYS_REPO"."CATALOG_OBJECTS_CREATED_BY_REPOSITORY_ACTIVATIONS"
--hdbtablefunction
--calculationview
--hdbprocedure
 
SELECT DISTINCT REPOSITORY_PACKAGE_ID, REPOSITORY_OBJECT_TYPE,'PRO' AS sitema, count(DISTINCT REPOSITORY_OBJECT_NAME ) AS num_view  
FROM "_SYS_REPO"."CATALOG_OBJECTS_CREATED_BY_REPOSITORY_ACTIVATIONS"
WHERE REPOSITORY_OBJECT_TYPE like 'calculationview%'
--AND REPOSITORY_PACKAGE_ID  = 'AreaSIBI.Proyectos.Maestras'
AND REPOSITORY_OBJECT_NAME LIKE   '%CDA_CLUB_VINOS_DOCUMENTO%'
group BY REPOSITORY_PACKAGE_ID,REPOSITORY_OBJECT_TYPE
ORDER BY REPOSITORY_PACKAGE_ID ASC, REPOSITORY_OBJECT_TYPE;

--"SYS"."VIEWS"
--"_SYS_REPO"."INACTIVE_OBJECT" quitar vistas inactivas


SELECT count(DISTINCT VIEW_NAME) FROM "SYS"."VIEWS" WHERE VIEW_TYPE = 'CALC' AND SCHEMA_NAME = '_SYS_BIC'



SELECT DISTINCT REPOSITORY_PACKAGE_ID, REPOSITORY_OBJECT_TYPE, REPOSITORY_OBJECT_NAME, count(DISTINCT REPOSITORY_OBJECT_NAME) AS num, 'FED1' AS sitema 
FROM "_SYS_REPO"."CATALOG_OBJECTS_CREATED_BY_REPOSITORY_ACTIVATIONS" 
WHERE REPOSITORY_OBJECT_NAME LIKE '%EXP_SFS%'
group BY REPOSITORY_PACKAGE_ID, REPOSITORY_OBJECT_TYPE,REPOSITORY_OBJECT_NAME
ORDER BY REPOSITORY_PACKAGE_ID ASC, REPOSITORY_OBJECT_TYPE,REPOSITORY_OBJECT_NAME;



SELECT * FROM sys.tables WHERE IS_SYSTEM_TABLE = 'FALSE'
